### ISSUE TITLE
Could you add a license file?

### ISSUE THREAD

**Issue by yuhangwang** [probmods/webchurch#73]
Could you add a license file to this project (preferably MIT license)? Thanks!

**Comment by longouyang** [comment]
@ngoodman does MIT sound good?

**Comment by yuhangwang** [comment]
Yes. Perfect. Thank you!

**Comment by ngoodman** [comment]
that seems fine with me for webchurch (that's the license for webppl too). 

(i don't think we're discussing it, but probmods/chapters should not be released under that license.)

**Comment by longouyang** [comment]
Okay! Added MIT license in c7b4eff5f24fca040d95782edbdfd904c60abec0

**Comment by yuhangwang** [comment]
Thanks!
