### ISSUE TITLE
Comments bug

### ISSUE THREAD

**Issue by toncho11** [probmods/webchurch#74]
If I add ";" and a comment the whole script crashes. 

I do execute it as follow on Windows 7:

node church scriptname.txt

**Comment by longouyang** [comment]
I can't reproduce this error -- can you provide the script you used?

**Comment by toncho11** [comment]
This is the file. It says: 1-19: Unclosed parens

[GoodMood.txt](https://github.com/probmods/webchurch/files/356991/GoodMood.txt)

**Comment by longouyang** [comment]
I tried your script on OS X and didn't get an error.

What version of webchurch are you running?

**Comment by toncho11** [comment]
It is on Windows, Windows, Windows...
I followed the non git instructions.

**Comment by longouyang** [comment]
Ah - I think I figured it out. Your file has both newlines `\n` and carriage returns `\r`.

webchurch doesn't like these, so you'll have to switch to an editor that doesn't insert carriage returns (also, make sure it saves the file as UTF-8)

**Comment by longouyang** [comment]
(Actually, it turns out this was an easy enough bug to fix, so if you install the latest webchurch that model should work now)
